---
# Welcome to my Home Assistant configuration!
#
# Don't be scared by the size of my configuration file...
# It is probably the smallest you've ever seen.
#
# My system is very modular and very differently structured
# compared to other configurations you'll find online.
#
# Basically, each file in the repository does 1 (one, uno, eins)
# thing only! Click through it, you'll get it pretty fast.
#
# The configuration.yaml is only used to bootstrap the system
# and contains some minimal, but vital, settings.
#
homeassistant:
  # Name of this Home Assistant instance... I've tried to be original... ;)
  name: Home

  # Location required to calculate the time the sun rises and sets
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret zone_home_elevation

  # metric for Metric, imperial for Imperial
  unit_system: !secret unit_system

  # Time zone
  # Pick yours from here:
  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone

  # Currency
  # Pick yours from here:
  # https://en.wikipedia.org/wiki/ISO_4217#Active_codes
  currency: EUR

  # URL Definition
  internal_url: !secret ha_url
  external_url: !secret ha_url

  # Load packages
  packages: !include_dir_named packages/

  # Whitelist External Directories
  allowlist_external_dirs: !secret whitelist_external_dirs

  # Auth Providerrs
  auth_providers:
    - type: homeassistant
    # List of trusted networks, consisting of IP addresses or networks,
    # that are allowed to bypass password protection when accessing Home Assistant.
#    - type: trusted_networks
#      trusted_networks: !secret trusted_networks
#      allow_bypass_login: false
#      trusted_users: !secret trusted_users

#remote_homeassistant:
#  instances:
#  - host: !secret casa_maurizio_host
#    port: 443
#    secure: true
#    access_token: !secret casa_maurizio_token
#    entity_prefix: "casa_maurizio_"

lovelace:
  resources: !include lovelace/resources.yaml
  dashboards:
    lovelace-tablet:
      mode: yaml
      title: Tablet
      icon: mdi:tablet
      show_in_sidebar: true
      require_admin: false
      filename: dashboard_tablet.yaml
    lovelace-management:
      mode: yaml
      title: Management
      icon: mdi:chart-bar-stacked
      show_in_sidebar: true
      require_admin: true
      filename: dashboard_management.yaml
    lovelace-test:
      mode: yaml
      title: Test
      icon: mdi:tune
      show_in_sidebar: true
      require_admin: true
      filename: dashboard_test.yaml

scene: !include scenes.yaml
